name: Docker CI for the conftopo-core image

on:
  push:
    paths:
      - 'requirements.txt'

jobs:
  docker:
    name: Docker job
    runs-on: ubuntu-latest
    steps:
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          file: docker/conftopo-core/Dockerfile
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: maduprey/conftopo-core:latest
